/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package playlist.view;

import java.io.*;
import java.util.*;

/**
 *
 * @author gfari
 */
public class Editar extends javax.swing.JFrame {

    private String nome;

    /**
     * Creates new form Editar
     */
    public Editar() {
        initComponents();
    }

    public void setNomeDaMusica(String nome) {
        this.nome = nome;
        carregarDadosMusica(); // Carregue os dados da música ao configurar o nome
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        confirmaredit = new javax.swing.JButton();
        fechar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        novonome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        novoartista = new javax.swing.JTextField();
        novoano = new javax.swing.JTextField();
        novoalbum = new javax.swing.JTextField();
        novogenero = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        confirmaredit.setText("confirmar");
        confirmaredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmareditActionPerformed(evt);
            }
        });

        fechar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        fechar.setText("x");
        fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("Edite as informaçoes da musica selecionada");

        novonome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novonomeActionPerformed(evt);
            }
        });

        jLabel2.setText("novo nome");

        novoartista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoartistaActionPerformed(evt);
            }
        });

        novoano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoanoActionPerformed(evt);
            }
        });

        novoalbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoalbumActionPerformed(evt);
            }
        });

        novogenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novogeneroActionPerformed(evt);
            }
        });

        jLabel3.setText("novo artista");

        jLabel4.setText("novo ano");

        jLabel5.setText("novo album");

        jLabel6.setText("novo genero");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(confirmaredit))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(fechar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(novogenero)
                            .addComponent(novoalbum)
                            .addComponent(novoano)
                            .addComponent(novoartista)
                            .addComponent(novonome, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(novonome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(novoartista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(novoano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(novoalbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(novogenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(confirmaredit))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void carregarDadosMusica() {
        try (BufferedReader br = new BufferedReader(new FileReader("musicas.txt"))) {
            String linha;
            while ((linha = br.readLine()) != null) {
                String[] campos = linha.split(",");

                if (campos.length >= 1 && campos[0].trim().equalsIgnoreCase(nome)) {
                    // Preencha os campos com as informações da música
                    novonome.setText(campos[0]);
                    novoartista.setText(campos[1]);
                    novoano.setText(campos[2]);
                    novoalbum.setText(campos[3]);
                    novogenero.setText(campos[4]);
                    nome = campos[0]; // Defina a variável nome com o nome da música atual
                    break; // Saia do loop, pois a música foi encontrada
                }
            }
        } catch (IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao ler o arquivo de músicas.");
            e.printStackTrace();
        }
    }
    private void novoartistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoartistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novoartistaActionPerformed

    private void novonomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novonomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novonomeActionPerformed

    private void novoanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novoanoActionPerformed

    private void novoalbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoalbumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novoalbumActionPerformed

    private void novogeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novogeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novogeneroActionPerformed

    private void confirmareditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmareditActionPerformed
        String novoNome = novonome.getText();
        String novoArtista = novoartista.getText();
        String novoAno = novoano.getText();
        String novoAlbum = novoalbum.getText();
        String novoGenero = novogenero.getText();

        // Verifique se algum campo está vazio
        if (novoNome.isEmpty() || novoArtista.isEmpty() || novoAno.isEmpty() || novoAlbum.isEmpty() || novoGenero.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Preencha todos os campos.");
            return;
        }

        // Crie uma lista temporária para armazenar as músicas atualizadas
        List<String> musicasAtualizadas = new ArrayList<>();

        try (BufferedReader br = new BufferedReader(new FileReader("musicas.txt"))) {
            String linha;
            while ((linha = br.readLine()) != null) {
                String[] campos = linha.split(",");
                if (campos.length >= 1 && campos[0].trim().equalsIgnoreCase(nome)) {
                    // Se a linha corresponder à música a ser editada, substitua pelos novos valores
                    musicasAtualizadas.add(String.join(",", novoNome, novoArtista, novoAno, novoAlbum, novoGenero));
                } else {
                    // Caso contrário, mantenha a linha original
                    musicasAtualizadas.add(linha);
                }
            }
        } catch (IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao ler o arquivo de músicas.");
            e.printStackTrace();
        }

        // Escreva as músicas atualizadas de volta no arquivo
        try (BufferedWriter bw = new BufferedWriter(new FileWriter("musicas.txt"))) {
            for (String musica : musicasAtualizadas) {
                bw.write(musica);
                bw.newLine();
            }
            javax.swing.JOptionPane.showMessageDialog(this, "Música editada com sucesso!");
            dispose(); // Feche a tela de edição após a conclusão
        } catch (IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao salvar as músicas editadas.");
            e.printStackTrace();
        }
    }//GEN-LAST:event_confirmareditActionPerformed

    private void fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_fecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmaredit;
    private javax.swing.JButton fechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField novoalbum;
    private javax.swing.JTextField novoano;
    private javax.swing.JTextField novoartista;
    private javax.swing.JTextField novogenero;
    private javax.swing.JTextField novonome;
    // End of variables declaration//GEN-END:variables
}
